---
name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pass gnupg
      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Trust gpg key
        run: |
          echo "510CC808500A036BAD375E5F3362F482D4DCE24C:6:" | gpg --import-ownertrust
          gpgconf --kill gpg-agent
      - name: Setup pass
        run: |
          pass init 510CC808500A036BAD375E5F3362F482D4DCE24C
      - name: Test pass functionality
        run: |
          echo "Generating test key with pass"
          pass generate -f test1 12
          echo "List added keys"
          pass
          echo "Fetch generated key"
          pass test1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --lib --verbose
